AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'Gemfile'
    - '*.gemspec'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.5.1

Naming/AccessorMethodName:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/StringLiterals:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*.rb'

Style/DoubleNegation:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Max: 20

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Security/YAMLLoad:
  Enabled: false